### PR TITLE
Fix fixing element whose box-sizing is border-box

### PR DESCRIPTION
**Pull request by jfcherng**
jQuery.height() is not counting padding in thus the sbstitute's height is wrong.

### CODE REVIEW

**Comment by shira-374** [comment]
`height()` is used on purpose, because the substitute should have the same padding as the original element (via CSS).

For example:

If the original element has `class="menu"` that applies some padding, then the substitute should also have `class="menu"` and thus the same padding. Using `.outerHeight()` in this case would make the substitute larger than it should be.

Does the element you are trying to fix have dynamic padding (via `style="..."` or JS) by any chance?

**Comment by jfcherng** [comment]
@ShiraNai7 Thanks for clarification. I would check it later.

**Comment by jfcherng** [comment]
@ShiraNai7 Found the culprit. The element I try to fix is using `box-sizing: border-box;`.

`.height()` get the height without padding but the height of a `border-box`-modeled element is counting border width and padding in.

---

Let's say the `border-box`-modeled element has the following layout.

Original: snipaste_2018-09-20_17-10-44 Substitute: snipaste_2018-09-20_17-17-41   

`$original.height()` would returns `46`. But `$substitute.height(46)` would set its height to `21`.
Because `21(height) + 24(padding) + 1 (border) = 46`.

**Comment by shira-374** [comment]
Thanks!

**Pull request merged**
